name: 'nest-app-filebeat'
logging.metrics.enabled: false
xpack.monitoring.enabled: false
setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "nest-app"
setup.template.pattern: "nest-app-*"
setup.ilm.enabled: false

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /usr/src/app/nestjs-logs/app*.log  
    fields:
      service: nestjs-app
    fields_under_root: true
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: 'message'

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  index: 'nest-app'
